# 🛠️ Chapter 2: Pre-model Workflow and Data Preprocessing
**Book Reference:** *scikit-learn Cookbook, Third Edition*

---

## 1. Introduction to Feature Engineering and Preprocessing
Machine learning algorithms are fundamentally mathematical optimization engines, making them exceptionally sensitive to the scale, format, and consistency of the input data matrix. Real-world raw data is inherently messy and poses major challenges to predictive modeling:

* **Scale Disparities:** High-magnitude numerical features will artificially dominate lower-magnitude vectors during weight optimization or spatial distance calculations.
* **Missing Structural Data:** Incomplete records containing null values or empty fields throw computational exceptions in most algorithmic execution blocks.
* **Categorical Formats:** Qualitative text elements cannot be natively interpreted by mathematical equations without being structurally mapped into linear numeric configurations.

This chapter details the precise methods required to clean, map, and transform messy, heterogeneous datasets into model-ready tensor inputs using the robust `scikit-learn` preprocessing ecosystem.

In [1]:
import numpy as np
import pandas as pd
from sklearn import preprocessing

# Create a synthetic, messy dataset with missing values and a massive extreme outlier (100,000)
raw_data = pd.DataFrame({
    'Age': [25, 30, np.nan, 45, 50],
    'Salary': [5000, 6000, 5500, 100000, 8000],  
    'City': ['Jakarta', 'Bandung', 'Jakarta', 'Surabaya', 'Bandung']
})
print("Raw Mixed Dataset:\n", raw_data)

Raw Mixed Dataset:
     Age    Salary      City
0  25.0      5000   Jakarta
1  30.0      6000   Bandung
2   NaN      5500   Jakarta
3  45.0    100000  Surabaya
4  50.0      8000   Bandung


## 2. Imputing Missing Values (Null Value Resolution)
Missing components—represented as `NaN` (Not a Number) entries—can cause major issues for algorithms like Support Vector Machines or Linear Regression. Rather than dropping incomplete records and risking losing valuable information, we use **Imputation** strategies to fill the gaps.

The `SimpleImputer` class provides a quick way to handle missing entries by evaluating existing non-null elements across a feature column:

* **Mean Strategy:** Replaces missing values with the average of the feature column. This works well for symmetric, normally distributed data but is highly sensitive to outliers.
* **Median Strategy:** Replaces missing values with the middle value of the sorted column. This is a much safer option for skewed data distributions since outliers don't pull the median away from the center.
* **Most Frequent / Mode Strategy:** Replaces missing gaps with the most common value in the column, making it ideal for categorical variables.

In this section, we use the **Median** strategy to safely fill the missing value in our `Age` vector without distortion.

In [2]:
from sklearn.impute import SimpleImputer

# Instantiate the imputer with a robust median replacement blueprint
imputer = SimpleImputer(strategy='median')

# Compute the median value on valid fields and transform the missing gaps
raw_data['Age_Imputed'] = imputer.fit_transform(raw_data[['Age']])
print("Post Imputation Results (Observe row 2 index):\n", raw_data[['Age', 'Age_Imputed']])

Post Imputation Results (Observe row 2 index):
     Age  Age_Imputed
0  25.0         25.0
1  30.0         30.0
2   NaN         37.5
3  45.0         45.0
4  50.0         50.0


## 3. Encoding Categorical Variables
Categorical data, such as city names, strings, or type classes, must be converted into numerical values. However, we have to match the encoding method to the nature of the categories:

### Ordinal Encoding vs. One-Hot Encoding
* **Ordinal Encoding:** Assigns a sequential integer to each category (e.g., `Low=0`, `Medium=1`, `High=2`). This should only be used when there is a clear, inherent ranking or order to the categories.
* **One-Hot Encoding:** Creates a separate binary column for every unique category found in the feature vector. Each row gets a `1` in the column corresponding to its category and a `0` everywhere else.

Using Ordinal Encoding on non-ordered features like `City` (`Jakarta=0`, `Bandung=1`, `Surabaya=2`) is a major mistake. It inadvertently forces a mathematical ranking on the model, implying that *Surabaya is twice as valuable as Bandung*. 

To prevent this false ranking, we use `OneHotEncoder` to give each city its own distinct spatial dimensions.

In [3]:
from sklearn.preprocessing import OneHotEncoder

# Set sparse_output=False to explicitly return a dense NumPy array rather than a sparse matrix pointer
ohe = OneHotEncoder(sparse_output=False)
kota_encoded = ohe.fit_transform(raw_data[['City']])

print("Identified Category Classes:", ohe.categories_)
print("\nOne-Hot Encoded Array Representation:\n", kota_encoded)

Identified Category Classes: [array(['Bandung', 'Jakarta', 'Surabaya'], dtype=object)]

One-Hot Encoded Array Representation:
 [[0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


## 4. Feature Scaling: StandardScaler vs. RobustScaler
When different features have wildly different ranges (e.g., ages spanning tens vs. salaries spanning thousands), models that rely on distance calculations can struggle. To fix this, we apply numerical scaling.

### The Math Behind the Scalers
The standard normalization technique is **`StandardScaler`**, which shifts and scales features to have a mean of 0 and a standard deviation of 1:

$$z = \frac{x - \mu}{\sigma}$$

Where $\mu$ is the explicit sample mean and $\sigma$ is the sample standard deviation. 

However, `StandardScaler` has a major flaw: it is highly sensitive to outliers. Because the mean and standard deviation calculations include every data point, a single extreme value will pull the mean toward it and artificially inflate the standard deviation. This squashes the normal data points into a tiny cluster, as shown in our results below.

To handle datasets with outliers, we use **`RobustScaler`**. Instead of using the mean and standard deviation, it scales data using the median and the Interquartile Range (IQR):

$$z = \frac{x - \text{median}}{IQR}$$

Where $IQR = Q_3 - Q_1$ (the distance between the 25th and 75th percentiles). 

By centering the data around the median and scaling with the IQR, `RobustScaler` keeps normal records well-spaced and clearly identifiable, isolating outliers without allowing them to break the scaling transformation.

In [4]:
from sklearn.preprocessing import StandardScaler, RobustScaler

standard_scaler = StandardScaler()
robust_scaler = RobustScaler()

salary_standard = standard_scaler.fit_transform(raw_data[['Salary']])
salary_robust = robust_scaler.fit_transform(raw_data[['Salary']])

print("StandardScaler Output (Distorted by Outlier):\n", salary_standard.flatten())
print("\nRobustScaler Output (Maintains Spacing for Normal Data):\n", salary_robust.flatten())

StandardScaler Output (Distorted by Outlier):
 [-0.52976518 -0.50314382 -0.5164545   1.99926459 -0.44990109]

RobustScaler Output (Maintains Spacing for Normal Data):
 [-0.4  0.  -0.2 37.6  0.8]


## 5. Designing Custom Transformations
Standard preprocessing tools handle common use cases, but real-world engineering often requires custom mathematical adjustments—like applying log transforms to handle highly skewed right-tailed distributions.

Instead of writing custom scaling operations manually using raw loops or pandas maps (which can introduce errors and cause data leakage), `scikit-learn` provides the **`FunctionTransformer`** wrapper. This tool turns any standard Python function or NumPy mapping vector into a fully functional, production-ready scikit-learn transformer component.

By wrapping functions in a `FunctionTransformer`, they gain native support for the `.fit()`, `.transform()`, and `.fit_transform()` lifecycle methods. This allows them to integrate perfectly into automated cross-validation workflows and deployment pipelines.

In [5]:
from sklearn.preprocessing import FunctionTransformer

# Define a log-transform using np.log1p (computes log(1 + x) to prevent divide-by-zero errors on 0 values)
# Set check_inverse=False to cleanly handle input DataFrames without validation warning flags
log_transformer = FunctionTransformer(np.log1p, check_inverse=False)

# Transform the skewed features using the functional pipeline component
salary_log = log_transformer.transform(raw_data[['Salary']])
print("Original Raw Salaries:\n", raw_data['Salary'].values)
print("\nLog-Transformed Salaries (Smoothed Variance Target):\n", salary_log.flatten())

Original Raw Salaries:
 [  5000   6000   5500 100000   8000]

Log-Transformed Salaries (Smoothed Variance Target):
 [ 8.51739317  8.6996814   8.61268517 11.51293546  8.98732181]
